Key Pair Auth

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -111,35 +111,35 @@ jobs:
         working-directory: terraform
 
       # Decode the private key and save it to a file
-      - name: Decode and save SSH private key
-        run: |
-          echo "${{ secrets.AZURE_PRIVATE_KEY }}" > private_key.pem
-          chmod 600 private_key.pem
+      # - name: Decode and save SSH private key
+      #   run: |
+      #     echo "${{ secrets.AZURE_PRIVATE_KEY }}" > private_key.pem
+      #     chmod 600 private_key.pem
 
-      # Test SSH Connection (Add verbosity for troubleshooting)
-      - name: Test SSH Connection
-        run: |
-          echo "Testing SSH connection to VM..."
-          ssh -i private_key.pem -o StrictHostKeyChecking=no -vvv azureuser@40.85.153.118 echo "SSH connection successful"
-        shell: bash
+      # # Test SSH Connection (Add verbosity for troubleshooting)
+      # - name: Test SSH Connection
+      #   run: |
+      #     echo "Testing SSH connection to VM..."
+      #     ssh -i private_key.pem -o StrictHostKeyChecking=no -vvv azureuser@40.85.153.118 echo "SSH connection successful"
+      #   shell: bash
 
       # Install Ansible
       - name: Install Ansible
         run: sudo apt-get install -y ansible
 
       # Configure Ansible Inventory
-      - name: Configure Ansible Inventory
-        run: |
-          echo "Configuring Ansible inventory file..."
-          echo "[azure_vm]" > inventory
-          echo "40.85.153.118 ansible_user=azureuser ansible_ssh_private_key_file=private_key.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no'" >> inventory
+      # - name: Configure Ansible Inventory
+      #   run: |
+      #     echo "Configuring Ansible inventory file..."
+      #     echo "[azure_vm]" > inventory
+      #     echo "40.85.153.118 ansible_user=azureuser ansible_ssh_private_key_file=private_key.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no'" >> inventory
           
-          if [[ ! -f "inventory" ]]; then
-            echo "Error: Ansible inventory file was not created."
-            exit 1
-          fi
+      #     if [[ ! -f "inventory" ]]; then
+      #       echo "Error: Ansible inventory file was not created."
+      #       exit 1
+      #     fi
 
-          echo "Ansible inventory file configured."
+      #     echo "Ansible inventory file configured."
 
       # Run Ansible Playbook
       - name: Run Ansible Playbook
