No ACR anymore

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -77,6 +77,7 @@ jobs:
         run: |
          terraform output
          terraform output -json
+       
       - name: Retrieve Public IP from Azure
         id: get_public_ip
         run: |
@@ -84,13 +85,31 @@ jobs:
             --resource-group ${{ env.RESOURCE_GROUP_NAME }} \
             --name Network-PIP \
             --query ipAddress -o tsv)
+          vm_name=$(terraform output -raw vm_name)  
           echo "public_ip=${PUBLIC_IP}" >> $GITHUB_ENV
+          echo "VM_NAME=${vm_name}" >> $GITHUB_ENV
 
       - name: Update Ansible inventory with VM IP
         run: |
           echo "[all]" > ansible/inventory.ini
           echo "${{ env.public_ip }} ansible_user=${{ env.ADMIN_USERNAME }} ansible_password=${{ env.ADMIN_PASSWORD }} ansible_connection=ssh ansible_port=22" >> ansible/inventory.ini
-
+      - name: Request JIT Access for VM
+        id: request_jit_access
+        run: |
+            az security jit-policy initiate --resource-group ${{ env.RESOURCE_GROUP_NAME }} \
+              --name ${{ env.VM_NAME }} \
+              --ports "22" \
+              --duration "PT1H"
+  
+      - name: Wait for JIT Access to be Granted
+        id: wait_for_jit_access
+        run: |
+            for i in {1..10}; do
+              nc -zvw3 ${{ env.public_ip }} 22 && echo "SSH is now accessible." && exit 0
+              echo "Waiting for SSH access to be granted..."
+              sleep 10
+            done
+            echo "Failed to establish SSH access." && exit 1
       - name: Install Ansible
         run: sudo apt-get update && sudo apt-get install -y ansible
 
